using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using ShopxBase.Domain.Entities;

namespace ShopxBase.Infrastructure.Data;

public static class DbInitializer
{
    public static async Task SeedRolesAndAdminAsync(IServiceProvider serviceProvider)
    {
        var roleManager = serviceProvider.GetRequiredService<RoleManager<IdentityRole>>();
        var userManager = serviceProvider.GetRequiredService<UserManager<AppUser>>();

        // Seed roles
        string[] roles = { "Admin", "Customer", "Staff", "Seller" };

        foreach (var role in roles)
        {
            if (!await roleManager.RoleExistsAsync(role))
            {
                await roleManager.CreateAsync(new IdentityRole(role));
                Console.WriteLine($"✅ Created role: {role}");
            }
        }

        // Auto create missing tables (e.g. ShopRatings)
        await EnsureTablesCreatedAsync(serviceProvider);

        // Seed admin user (optional)
        var adminEmail = "admin@shopxbase.com";
        var adminUser = await userManager.FindByEmailAsync(adminEmail);

        if (adminUser == null)
        {
            var admin = new AppUser
            {
                UserName = "admin",
                Email = adminEmail,
                FullName = "System Administrator",
                Occupation = "Admin",
                Address = "System",
                Avatar = "",
                token = "",
                EmailConfirmed = true,
                CreatedAt = DateTime.UtcNow
            };

            var result = await userManager.CreateAsync(admin, "Admin@123");

            if (result.Succeeded)
            {
                await userManager.AddToRoleAsync(admin, "Admin");
                Console.WriteLine($"✅ Created admin user: {adminEmail}");
            }
            else
            {
                Console.WriteLine($"❌ Failed to create admin: {string.Join(", ", result.Errors.Select(e => e.Description))}");
            }
        }
    }

    public static async Task EnsureTablesCreatedAsync(IServiceProvider serviceProvider)
    {
        try
        {
            var context = serviceProvider.GetRequiredService<ShopxBaseDbContext>();
            await context.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS public.""ShopRatings"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ShopId"" integer NOT NULL,
                    ""UserId"" text NOT NULL,
                    ""Star"" integer NOT NULL,
                    ""Comment"" text NOT NULL,
                    ""IsApproved"" boolean NOT NULL DEFAULT TRUE,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    ""UpdatedAt"" timestamp with time zone NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                    CONSTRAINT ""PK_ShopRatings"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ShopRatings_Shops_ShopId"" FOREIGN KEY (""ShopId"") REFERENCES public.""Shops"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_ShopRatings_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES public.""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_ShopRatings_ShopId"" ON public.""ShopRatings"" (""ShopId"");
                CREATE INDEX IF NOT EXISTS ""IX_ShopRatings_UserId"" ON public.""ShopRatings"" (""UserId"");

                CREATE TABLE IF NOT EXISTS public.""ShopWallets"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ShopId"" integer NOT NULL,
                    ""AvailableBalance"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""PendingBalance"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""TotalWithdrawn"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""BankName"" text NULL,
                    ""BankAccountNumber"" text NULL,
                    ""BankAccountHolder"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    ""UpdatedAt"" timestamp with time zone NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                    CONSTRAINT ""PK_ShopWallets"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ShopWallets_Shops_ShopId"" FOREIGN KEY (""ShopId"") REFERENCES public.""Shops"" (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_ShopWallets_ShopId"" ON public.""ShopWallets"" (""ShopId"");

                CREATE TABLE IF NOT EXISTS public.""WalletTransactions"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ShopId"" integer NOT NULL,
                    ""OrderId"" integer NULL,
                    ""Amount"" numeric(18,2) NOT NULL,
                    ""Type"" integer NOT NULL,
                    ""Description"" text NOT NULL DEFAULT '',
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    ""UpdatedAt"" timestamp with time zone NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                    CONSTRAINT ""PK_WalletTransactions"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_WalletTransactions_Shops_ShopId"" FOREIGN KEY (""ShopId"") REFERENCES public.""Shops"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS public.""WithdrawalRequests"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ShopId"" integer NOT NULL,
                    ""Amount"" numeric(18,2) NOT NULL,
                    ""BankName"" text NOT NULL,
                    ""BankAccountNumber"" text NOT NULL,
                    ""BankAccountHolder"" text NOT NULL,
                    ""Status"" integer NOT NULL DEFAULT 0,
                    ""ProcessedAt"" timestamp with time zone NULL,
                    ""Note"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    ""UpdatedAt"" timestamp with time zone NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                    CONSTRAINT ""PK_WithdrawalRequests"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_WithdrawalRequests_Shops_ShopId"" FOREIGN KEY (""ShopId"") REFERENCES public.""Shops"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS public.""OrderDisputes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""OrderId"" integer NOT NULL,
                    ""UserId"" text NOT NULL,
                    ""Reason"" text NOT NULL,
                    ""EvidenceUrls"" text NULL,
                    ""Status"" integer NOT NULL DEFAULT 0,
                    ""ResolutionNote"" text NULL,
                    ""ResolvedAt"" timestamp with time zone NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    ""UpdatedAt"" timestamp with time zone NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                    CONSTRAINT ""PK_OrderDisputes"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_OrderDisputes_Orders_OrderId"" FOREIGN KEY (""OrderId"") REFERENCES public.""Orders"" (""Id"") ON DELETE CASCADE
                );
            ");
            Console.WriteLine("✅ Checked/Created Escrow & Wallet tables successfully.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"⚠️ Error ensuring Escrow tables: {ex.Message}");
        }
    }
}
